// This file is auto-generated by @hey-api/openapi-ts


export type $OpenApiTs = {
    '/umbraco/time/api/v1/time/date': {
        get: {
            res: {
                /**
 * Success
 */
                200: string;
            };
        };
    };
    '/umbraco/time/api/v1/time/time': {
        get: {
            res: {
                /**
 * Success
 */
                200: string;
            };
        };
    };
};