// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GetUmbracoTimeApiV1TimeDateResponse, GetUmbracoTimeApiV1TimeTimeResponse } from './types.gen';

/**
 * @returns string OK
 * @throws ApiError
 */
export const getUmbracoTimeApiV1TimeDate = (): CancelablePromise<GetUmbracoTimeApiV1TimeDateResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/umbraco/time/api/v1/time/date'
}); };

/**
 * @returns string OK
 * @throws ApiError
 */
export const getUmbracoTimeApiV1TimeTime = (): CancelablePromise<GetUmbracoTimeApiV1TimeTimeResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/umbraco/time/api/v1/time/time'
}); };