// This file is auto-generated by @hey-api/openapi-ts


import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { $OpenApiTs } from './models.gen';

export class TimeService {
    /**
 * @returns string Success
 * @throws ApiError
 */
    public static getDate(): CancelablePromise<$OpenApiTs['/umbraco/time/api/v1/time/date']['get']['res'][200]> {
        return __request(OpenAPI, {
    method: 'GET',
    url: '/umbraco/time/api/v1/time/date'
});
    }
    
    /**
 * @returns string Success
 * @throws ApiError
 */
    public static getTime(): CancelablePromise<$OpenApiTs['/umbraco/time/api/v1/time/time']['get']['res'][200]> {
        return __request(OpenAPI, {
    method: 'GET',
    url: '/umbraco/time/api/v1/time/time'
});
    }
    
}