// This file is auto-generated by @hey-api/openapi-ts

export type GetUmbracoTimeApiV1TimeDateResponse = string;

export type GetUmbracoTimeApiV1TimeTimeResponse = string;

export type $OpenApiTs = {
    '/umbraco/time/api/v1/time/date': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: string;
            };
        };
    };
    '/umbraco/time/api/v1/time/time': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: string;
            };
        };
    };
};